language: go

go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  
after_success:
  - goveralls -service=travis-ci
